import { Inter } from "next/font/google";
import "./globals.css";

import Header from "../components/header";
import { AppWrapper } from "/src/context/context.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shef's Foods",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <AppWrapper>
          <Header />
          {children}
          </AppWrapper>
        </body>
      </html>
    </>
  );
}
